apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env-config
  namespace: demo-apps
data:
  env-config.js: |
    window._env_ = {
      BACKEND_URL: "http://demo-backend.demo-apps.svc.cluster.local:8000"
    };
