apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
        - name: demo-frontend
          image: ghcr.io/recmanj/demo-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: env-config
              mountPath: /usr/share/nginx/html/env-config.js
              subPath: env-config.js
      volumes:
        - name: env-config
          configMap:
            name: frontend-env-config
