name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: recmanj/shared-workflows/.github/workflows/build-push-image.yaml@main
    with:
      image_name: recmanj/demo-frontend
    permissions:
      contents: read
      packages: write
